# syntax=docker/dockerfile:1

FROM golang:1.19 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

ENV PORT 9090

RUN make build-server

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /app/ /app/

EXPOSE 9090/tcp

CMD ["/app/bin/fhird", "--verbose"]

